// <auto-generated />
using System;
using DiscussionWeb.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscussionWeb.Data.Migrations
{
    [DbContext(typeof(DiscussionWebDbContext))]
    [Migration("20200621205118_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiscussionWeb.Data.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Permission")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            FirstName = "Tony",
                            LastName = "Stark",
                            NickName = "Ironman",
                            Permission = (byte)1,
                            Registered = new DateTime(2020, 6, 21, 20, 51, 18, 171, DateTimeKind.Utc).AddTicks(1076),
                            RegistrationEmail = "iron@man.cz"
                        },
                        new
                        {
                            Id = new Guid("b28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            FirstName = "Bruce",
                            LastName = "Wayne",
                            NickName = "Batman",
                            Permission = (byte)1,
                            Registered = new DateTime(2020, 6, 21, 20, 51, 18, 171, DateTimeKind.Utc).AddTicks(1497),
                            RegistrationEmail = "bat@man.cz"
                        });
                });

            modelBuilder.Entity("DiscussionWeb.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<long>("NumberOfEdits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28c1db41-f104-46e6-8943-d31c0291e0e3"),
                            LastEdited = new DateTime(2020, 6, 21, 20, 51, 18, 180, DateTimeKind.Utc).AddTicks(466),
                            Message = "Hello world!",
                            NumberOfEdits = 0L,
                            Posted = new DateTime(2020, 6, 21, 20, 51, 18, 180, DateTimeKind.Utc).AddTicks(140),
                            ThreadId = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b")
                        },
                        new
                        {
                            Id = new Guid("d94a64c2-2e8f-4162-9976-0ffe03d30767"),
                            LastEdited = new DateTime(2020, 6, 21, 20, 51, 18, 180, DateTimeKind.Utc).AddTicks(1114),
                            Message = "Hello csharp!",
                            NumberOfEdits = 0L,
                            Posted = new DateTime(2020, 6, 21, 20, 51, 18, 180, DateTimeKind.Utc).AddTicks(1099),
                            ThreadId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97")
                        });
                });

            modelBuilder.Entity("DiscussionWeb.Data.Models.Thread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<long>("NumberOfEdits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Threads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            AuthorId = new Guid("a28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "A general discussion about life universe and everything",
                            LastEdited = new DateTime(2020, 6, 21, 20, 51, 18, 179, DateTimeKind.Utc).AddTicks(3302),
                            NumberOfEdits = 0L,
                            Posted = new DateTime(2020, 6, 21, 20, 51, 18, 179, DateTimeKind.Utc).AddTicks(2929),
                            Title = "General Discussion"
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            AuthorId = new Guid("b28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "A general discussion about C#.",
                            LastEdited = new DateTime(2020, 6, 21, 20, 51, 18, 179, DateTimeKind.Utc).AddTicks(3981),
                            NumberOfEdits = 0L,
                            Posted = new DateTime(2020, 6, 21, 20, 51, 18, 179, DateTimeKind.Utc).AddTicks(3969),
                            Title = "Csharp Discussion"
                        });
                });

            modelBuilder.Entity("DiscussionWeb.Data.Models.Post", b =>
                {
                    b.HasOne("DiscussionWeb.Data.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId");

                    b.HasOne("DiscussionWeb.Data.Models.Thread", "Thread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId");
                });

            modelBuilder.Entity("DiscussionWeb.Data.Models.Thread", b =>
                {
                    b.HasOne("DiscussionWeb.Data.Models.Author", "Author")
                        .WithMany("Threads")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
